name: Generate data and open PR

on:
  pull_request:
    types: [labeled]
  schedule:
    - cron:  '0 8 * * *'
jobs:
  generate-and-open-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Generate data
        run: |
          npm install
          npm run generate
          ls ./data
      - name: Create Pull Request
        uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          title: "Updates to COVID-19 data"
          body: "Updated json files in the `./data` folder with new COVID-19 data"
          branch: "covid-data-update-${{ hashFiles('./data/us.json') }}"
          commit-message: "New data files"
