name: Generate data

on:
  pull_request:
    types: [labeled]
  schedule:
    - cron:  '0 8 * * *'
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Generate data
        run: |
          npm install
          npm run generate
          ls ./data
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          source_branch: "covid-data-update-${{ hashFiles('./data/denmark.json') }}"
          destination_branch: "main"
          # pr_title: "Pulling ${{ github.ref }} into master" # Title of pull request
          # pr_body: ":crown: *An automated PR*"              # Full markdown support, requires pr_title to be set
          pr_assignee: "bence-toth"
